name: Run test suite

on:
  push:
    branches:
      - main
      - next
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Set node version to ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run Vitest
        run: pnpm test --run
