name: Run test suite

on:
  push:
    branches:
      - main
      - next
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"

      - uses: pnpm/action-setup@v2
        name: Install dependencies
        with:
          version: 8
          run_install: true

      - name: Run Vitest
        run: pnpm test --run
